### ISSUE TITLE
GAT example runtime error

### ISSUE THREAD

**Issue by YukeWang96** [xiezhq-hermann/graphiler#10]
Hi,

When I run 
```
docker run --gpus all -i -t graphiler python examples/GAT/GAT.py pubmed 500
``` 
by following `README.md`, I notice the following error, is there any solution to this? Thanks!
```
benchmarking on: pubmed
  NumNodes: 19717
  NumEdges: 88651
  NumFeats: 500
  NumClasses: 3
  NumTrainingSamples: 60
  NumValidationSamples: 500
  NumTestSamples: 1000
Done loading data from cached files.
  NumNodes: 19717
  NumEdges: 88651
  NumFeats: 500
  NumClasses: 3
  NumTrainingSamples: 60
  NumValidationSamples: 500
  NumTestSamples: 1000
Done loading data from cached files.
3-Graphiler elapsed time: 1.25946044921875 ms/infer
intermediate data memory usage: 20.33837890625 MB
0-DGL-UDF elapsed time: 109.48782444000244 ms/infer
intermediate data memory usage: 433.49072265625 MB
Traceback (most recent call last):
  File "GAT.py", line 183, in <module>
    profile(sys.argv[1], int(sys.argv[2]), repeat)
  File "GAT.py", line 133, in profile
    run_baseline_graphiler(g, features)
  File "/opt/conda/lib/python3.8/site-packages/graphiler-0.0.1-py3.8-linux-x86_64.egg/graphiler/utils/bench.py", line 63, in wrapper
    func(*args, **kwargs)
  File "GAT.py", line 106, in run_baseline_graphiler
    check_equal(compile_res, res)
  File "/opt/conda/lib/python3.8/site-packages/graphiler-0.0.1-py3.8-linux-x86_64.egg/graphiler/utils/bench.py", line 14, in check_equal
    np.testing.assert_allclose(first.cpu().detach(
  File "/opt/conda/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 1527, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/opt/conda/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.001, atol=0

Mismatched elements: 430 / 1261888 (0.0341%)
Max absolute difference: 17.518066
Max relative difference: 0.00428651
 x: array([[4234.9517, 4136.021 , 4445.831 , ..., 4311.138 , 4854.3755,
        4461.5225],
       [4109.9897, 4010.034 , 4315.6206, ..., 4189.983 , 4713.985 ,...
 y: array([[4234.9517, 4136.021 , 4445.831 , ..., 4311.138 , 4854.3755,
        4461.5225],
       [4109.9897, 4010.034 , 4315.6206, ..., 4189.983 , 4713.985 ,...
```

**Comment by xiezhq-hermann** [comment]
Hi @YukeWang96, the numeric difference is introduced by difference implementation of kernels for `seg_softmax` and sometimes can raise a runtime error when the difference exceeded the threshold, which was not set based on strict mathematic properties but rule of thumb. As you can see from the error message, the two tensors are mostly the same and actually do no harm on the final result. You can relax the threshold [here](https://github.com/xiezhq-hermann/graphiler/blob/main/python/graphiler/utils/bench.py#L15) to avoid the error.
Feel free to reach out if find a real numeric error in execution. Thanks for your interest in Graphiler!

**Comment by YukeWang96** [comment]
Got it, thanks!
