### ISSUE TITLE
Aggregation Methods in reduce_func

### ISSUE THREAD

**Issue by iquitap** [xiezhq-hermann/graphiler#13]
While using Graphiler, I attempted to use the max or mean functions as alternatives to sum within the reduce_func parameter. Unfortunately, this led to an error message: dgl_ FFI. base. DGLError: Expect number of features to match number of nodes (len (u)).

I'm not sure if the reason for this error is from whether the current reduce_func doesn't support these two aggregation methods?

**Comment by xiezhq-hermann** [comment]
Max or Mean should be supported, thus there might be some compatibility issues with latest update of DGL. Does sum work at the same scenario?

**Comment by iquitap** [comment]
My testing process was using the docker environment provided in the readme file. So I guess it shouldn't likely be an issue due to the DGL version.

However, based on the MOVEMENT_MAP function in the link below, it seems due to the existing version not having support for parsing for aggregator mean and max? Looking forward and thanking you for your guidance if I've misunderstood somewhere.

https://github.com/xiezhq-hermann/graphiler/blob/ddba5ba1df518d555012ef597ad24c308d752583/src/builder/builder.cpp#L20C56-L20C68

I attach my test code and error message below for your convenience.

```python
def message_func(edges: EdgeBatchDummy):
    return {'m': edges.src['h']}


def reduce_func(nodes: NodeBatchDummy):
    return {'h': torch.max(nodes.mailbox['m'], dim=1)}


mpdfg = mpdfg_builder(message_func, reduce_func)


class TESTLayer(nn.Module):
    def __init__(self, in_dim, out_dim):
        super(TESTLayer, self).__init__()
        self.weight = torch.rand(in_dim, out_dim).to(device)

    def forward(self, g, feature, compile=False):
        g.ndata['h'] = feature
        if compile:
            update_all(g, mpdfg)
        else:
            g.update_all(message_func, reduce_func)
        return g.ndata.pop('h')


class TEST(nn.Module):
    def __init__(self, in_dim, hidden_dim, out_dim):
        super(TEST, self).__init__()

        self.layer1 = TESTLayer(in_dim, hidden_dim)
        self.layer2 = TESTLayer(hidden_dim, out_dim)

    def forward(self, g, features, compile=False):
        x = F.relu(self.layer1(g, features, compile))
        x = self.layer2(g, x, compile)
        return x
``` 

`
Traceback (most recent call last):
  File "test.py", line 120, in <module>
    profile(sys.argv[1], int(sys.argv[2]), int(sys.argv[3]), repeat)
  File "test.py", line 102, in profile
    run_baseline_and_graphiler(g, features)
  File "/home/swlu/miniconda3/lib/python3.8/site-packages/graphiler-0.0.1-py3.8-linux-x86_64.egg/graphiler/utils/bench.py", line 65, in wrapper
    func(*args, **kwargs)
  File "test.py", line 72, in run_baseline_and_graphiler
    compile_res = bench(net=net, net_params=(
  File "/home/swlu/miniconda3/lib/python3.8/site-packages/graphiler-0.0.1-py3.8-linux-x86_64.egg/graphiler/utils/bench.py", line 23, in bench
    net(*net_params)
  File "/home/swlu/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "test.py", line 52, in forward
    x = F.relu(self.layer1(g, features, compile))
  File "/home/swlu/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "test.py", line 38, in forward
    update_all(g, mpdfg)
  File "/home/swlu/miniconda3/lib/python3.8/site-packages/graphiler-0.0.1-py3.8-linux-x86_64.egg/graphiler/update_all.py", line 5, in update_all
    g.ndata[key] = updated[key]
  File "/home/swlu/miniconda3/lib/python3.8/site-packages/dgl/view.py", line 81, in __setitem__
    self._graph._set_n_repr(self._ntid, self._nodes, {key : val})
  File "/home/swlu/miniconda3/lib/python3.8/site-packages/dgl/heterograph.py", line 3990, in _set_n_repr
    nfeats = F.shape(val)[0]
  File "/home/swlu/miniconda3/lib/python3.8/site-packages/dgl/backend/pytorch/tensor.py", line 67, in shape
    return input.shape
AttributeError: 'tuple' object has no attribute 'shape'
`

**Comment by xiezhq-hermann** [comment]
Hi @iquitap thank you for the feedback, and yes I just found that we forgot to put mean and avg operator in the artifact release. If you are looking for a hack fix for your experiment, you can simply replace "sum" [here](https://github.com/xiezhq-hermann/graphiler/blob/ddba5ba1df518d555012ef597ad24c308d752583/src/ops/dgl_primitives/spmm.cu#L370C19-L370C19) with "max" and create a new op like SpMMEdgeMax and then add a rule in the place you pointed to map a max aggregation operator to it.
Hope it helps. Let me know if you might have any further questions.
